### ISSUE TITLE
Overflow with >10 variables

### ISSUE THREAD

**Issue by samotracio** [jfcrenshaw/pzflow#81]
Hi,
pzflow seems to work fantastically. I am wondering if there is a hard limit on the nr. of columns that it can handle. Whenever I feed a table with 10 or more columns I get an overflow error when doing flow.train(). This is independent of the dataset and even when all paremeters, bijectors, etc. are set at their default values. Thanks.

---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
<timed exec> in <module>

~/a3/envs/tenf/lib/python3.9/site-packages/pzflow/flow.py in train(self, inputs, epochs, batch_size, optimizer, loss_fn, convolve_errs, patience, seed, verbose, progress_bar)
    999         X = jnp.array(inputs[columns].to_numpy())
   1000         C = self._get_conditions(inputs)
-> 1001         losses = [loss_fn(model_params, X, C)]
   1002         if verbose:
   1003             print(f"(0) {losses[-1]:.4f}")

    [... skipping hidden 11 frame]

~/a3/envs/tenf/lib/python3.9/site-packages/pzflow/flow.py in loss_fn(params, x, c)
    941             @jit
    942             def loss_fn(params, x, c):
--> 943                 return -jnp.mean(self._log_prob(params, x, c))
    944 
    945         # initialize the optimizer

~/a3/envs/tenf/lib/python3.9/site-packages/pzflow/flow.py in _log_prob(self, params, inputs, conditions)
    400         # calculate log_prob
    401         u, log_det = self._forward(params[1], inputs, conditions=conditions)
--> 402         log_prob = self.latent.log_prob(params[0], u) + log_det
    403         # set NaN's to negative infinity (i.e. zero probability)
    404         log_prob = jnp.nan_to_num(log_prob, nan=jnp.NINF)

~/a3/envs/tenf/lib/python3.9/site-packages/pzflow/distributions.py in log_prob(self, params, inputs)
    437 
    438         # calculate log_prob
--> 439         prob = mask / (2 * self.B) ** self.input_dim
    440         prob = jnp.where(prob == 0, epsilon, prob)
    441         log_prob = jnp.log(prob)

    [... skipping hidden 1 frame]

~/a3/envs/tenf/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py in deferring_binary_op(self, other)
   4934     args = (other, self) if swap else (self, other)
   4935     if isinstance(other, _accepted_binop_types):
-> 4936       return binary_op(*args)
   4937     if isinstance(other, _rejected_binop_types):
   4938       raise TypeError(f"unsupported operand type(s) for {opchar}: "

    [... skipping hidden 6 frame]

~/a3/envs/tenf/lib/python3.9/site-packages/jax/_src/dtypes.py in _scalar_type_to_dtype(typ, value)
    168   if typ is int and value is not None:
    169     if value < np.iinfo(dtype).min or value > np.iinfo(dtype).max:
--> 170       raise OverflowError(f"Python int {value} too large to convert to {dtype}")
    171   return dtype
    172 

OverflowError: Python int 10000000000 too large to convert to int32

**Comment by jfcrenshaw** [comment]
Ohh that is really interesting -- thanks for pinpointing where this error arises.

There is an easy fix I can push: rather than taking the log of the probability, I can directly calculate the log_prob. (essentially `log(B ** D)` --> `D * log(B)`). I will push a fix later today once my meetings are over.

I do not know of any other issues that will cause a problem with the precision, but if you find any, please let me know, and I will fix them ASAP.

**Comment by jfcrenshaw** [comment]
@samotracio this should be fixed now. Let me know if the problem persists.

**Comment by samotracio** [comment]
Great! Tanks for your prompt reply. I am on holidays right now, but will be back in a week to keep flowing
