### ISSUE TITLE
Is it possible to draw conditional samples?

### ISSUE THREAD

**Issue by fountaindive** [jfcrenshaw/pzflow#93]
Hello,

I was wondering if the following is possible with pzflow.

Suppose we have a 2D dataset e.g (x, y) and we fit a normalising flow model to it.

Can we draw samples from p(x|y=some value) ?

Thanks!

**Comment by MrShoenel** [comment]
I have used pzflow for a while now, so yes, it's perfectly possible! When you create the flow object, you can pass in a list of conditional columns:

```python
flow = Flow(data_columns=['x', 'y'], conditional_columns=['y'], ...) # more arguments
```

It even allows you to inspect the posterior distribution.

**Comment by fountaindive** [comment]
Hi @MrShoenel thanks for the reply! Ah I see, so that's marginalising 'x' over 'y' right?

What about generating samples of 'x' for a given value of 'y' though?

Cheers

**Comment by MrShoenel** [comment]
When instantiating the Flow, you might as well condition over **both** columns/features in this case (however, that only makes sense for when you have additional columns/features of course):

```python
flow = Flow(data_columns=['x', 'y', ...], conditional_columns=['x', 'y'], ...) # more arguments
```
Alternatively, train a second flow that conditions on `x` instead (I think this is your only option if you really only have 2 features):

```python
flow = Flow(data_columns=['x', 'y'], conditional_columns=['x'], ...) # more arguments
```

How does your data look? Is it really only 2-dimensional? What were your results so far with pzflow?

**Comment by fountaindive** [comment]
I'm not sure conditional columns will work for me but I haven't spent time to understand how they work to be fair.

2D is just an example, I'm working with N-D really. Ideally, I'd like to condition on any of the columns and any of them, or a combination of them to some fixed values then sample the rest.

I have an approximate way to sample from `p(x|y=y_*)` where y_* is some fixed value but I was curious if normalising flows could do this exactly.

I've used pzflow on and off for a year now and I've always gotten really great results with it (so long as the dimension isn't too high, but that's understandable)

**Comment by fountaindive** [comment]
but yeah this is quite an old issue and can probably be closed tbh - I don't want to waste your time!
